### ISSUE TITLE
ステージ１をクリアしたことを保存したい

### ISSUE THREAD

**Issue by ryosangataRYOSAN** [Teramon1031/originalGame#21]
### セーブ用のスクリプトを用意しよう！
- ClearHanteiScriptを以下のようにしてもOK！
![image](https://user-images.githubusercontent.com/19717221/29853419-c9129534-8d7a-11e7-930a-e74f1be126b5.png)

### セーブを変更するときはこのコードを追加しよう
![image2](https://user-images.githubusercontent.com/19717221/29853565-a08eb5a6-8d7b-11e7-922a-a0fd2bbec8c1.jpg)

### ロードするときはこれ！
![image3](https://user-images.githubusercontent.com/19717221/29853616-ec55bf66-8d7b-11e7-8e30-2d809bbf3dc1.jpg)

### 具体的にどうなっているのか
- クリアの判定をint型で保存するようにそれっぽくしてるよ！
- SaveCleared(int a)　のaの値でクリアしてるかどうかを変更するよ
- 今は1の時がstage1クリア，0の時が未クリアにしてます．これは単純にif文で決めてるだけなので簡単に変更できる！ステージ追加にも簡単に対応！

### おまけ
- PlayerScriptでOnCollisionEnterじゃなくてOnColliderEnterになってた(画像2枚目の赤い部分)けど間違いかな？
- おそくなってごめんね！わかんない部分あればコメントでがしがし聞いてね

**Comment by Teramon1031** [comment]
コミットしてからこれを見ました汗
だからunityちゃんの当たり判定がおかしかったのか…
