### ISSUE TITLE
Unityちゃんを追従するカメラの位置をInspector上で変えても再生すると後ろの方になって場所が変えられない

### ISSUE THREAD

**Issue by ryosangataRYOSAN** [Teramon1031/originalGame#3]
## 原因
unity-chanの子オブジェクトの中にあるカメラについているThirdPersonCameraっていうスクリプトがカメラの座標をコントロールしてるからinspecterとは違う場所に行ってしまう

### スクリプトを無効にする
- メリット　：　簡単
- デメリット：　スクリプトが良さげにしてくれている部分もあるのでそれがなくなる
### スクリプト上でカメラを配置したい場所を指定する
- メリット　：　スクリプトが良さげにしてくれている部分が今と同じ状態を維持できる
- デメリット：　変更により良さげになっている状態が変わってしまうかもしれない
- Camerasの中にある他のオブジェクトの座標を参考しているのでそれの座標を変えれば良い．通常時はstandardposオブジェクトを参照しているよ

**Comment by Teramon1031** [comment]
できました！CamPosの座標を変えました。ありがとうございます！

**Comment by ryosangataRYOSAN** [comment]
👍
その調子で頑張っていこう
