### ISSUE TITLE
敵を視界外でうまく生成できない

### ISSUE THREAD

**Issue by ryosangataRYOSAN** [Teramon1031/originalGame#8]
## 原因
- シーンカメラの除外ができていなかった
- updateの初めにIsRendereredをfalseにしていたのでせっかくのOnWillRenderObjectでの処理が上書きされちゃっていた
## おまけ
- timerの値が最初に定義されていなかったから定義しよう

## 修正後のスクリプト
![20170806-174952](https://user-images.githubusercontent.com/19717221/29001890-f03d9a90-7acf-11e7-99b2-c9ff807f8c97.png)

**Comment by Teramon1031** [comment]
できました！ありがとうございます！毎フレームfalseにしたら意味なくなっちゃうんですね…
#if UNITY_EDTORと#endifはどういう意味でしょうか？調べたら意味がわかりませんでした

**Comment by ryosangataRYOSAN** [comment]
簡単に言うと今，どんな状態でUnityが動いているかを参照するコードなんだ
条件にあっていればif文の中をコンパイルするし，あっていなければコンパイルしない
#if UNITY_EDTOR　は，エディター上での実行なら，if文の中のコードをコンパイルする．
もしエディタ以外（ビルド済み）であればif文の中をコンパイルしなくなるんだ！
#endifはその名の通りifの終了地点だね

今回の場合は，カメラに写っているかの判定を取りたいんだけど，実はOnWillRenderObjectはシーンビューのカメラも判定の対象になってしまう．だから#if UNITY_EDTORでエディターで実行の時だけシーンビューカメラを対象から外すって処理をするように書いているんだ

https://dobon.net/vb/dotnet/programing/define.html
https://docs.unity3d.com/ja/current/Manual/PlatformDependentCompilation.html

**Comment by Teramon1031** [comment]
あ、ビルドした後にそのスクリプトが残っていると、シーンカメラがなくエラーが出ちゃうからエディター上で実行している時だけスクリプトを実行している、ということでしょうか？

**Comment by ryosangataRYOSAN** [comment]
大正解！それで１００％あってる！
